services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: balendar
      POSTGRES_USER: balendar
      POSTGRES_PASSWORD: balendar_dev
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
